openapi: '3.0.2'
info:
    title: Calculator
    version: '1.0'
servers:
    - url: http://localhost:9000
paths:
    /history:
        get:
            description: Retrieves all the operations
            operationId: getHistory
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        operation:
                                            type: string
                                        args:
                                            type: object
                                            properties:
                                                first:
                                                    type: number
                                                second:
                                                    type: number
                                        result:
                                            type: number
    /add:
        get:
            description: Adds two numbers
            operationId: add
            parameters:
                - in: query
                  name: first
                  description: First argument
                  schema:
                      type: number
                - in: query
                  name: second
                  description: Second argument
                  schema:
                      type: number
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: number
    /subtract:
        get:
            description: Subtracts two numbers
            operationId: subtract
            parameters:
                - in: query
                  name: first
                  description: First argument
                  schema:
                      type: number
                - in: query
                  name: second
                  description: Second argument
                  schema:
                      type: number
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: number
    /multiply:
        get:
            description: Multiplies two numbers
            operationId: multiply
            parameters:
                - in: query
                  name: first
                  description: First argument
                  schema:
                      type: number
                - in: query
                  name: second
                  description: Second argument
                  schema:
                      type: number
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: number
    /divide:
        get:
            description: Divedes two numbers
            operationId: divide
            parameters:
                - in: query
                  name: first
                  description: First argument
                  schema:
                      type: number
                - in: query
                  name: second
                  description: Second argument
                  schema:
                      type: number
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: number
                '400':
                    description: Bad Request
    /modulo:
        get:
            description: Calculates the modulo of two numbers
            operationId: modulo
            parameters:
                - in: query
                  name: first
                  description: First argument
                  schema:
                      type: number
                - in: query
                  name: second
                  description: Second argument
                  schema:
                      type: number
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: number
                '400':
                    description: Bad Request
